name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install VSCE
      run: npm install -g @vscode/vsce
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx tsc

    - name: Package
      run: vsce package -o banjo-language.vsix

    - name: Release
      run: |
        gh release create \
          -t "banjo-vscode ${{ inputs.version }}" \
          -n "banjo-vscode ${{ inputs.version }}" \
          "v${{ inputs.version }}" \
          banjo-language.six
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
