name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install VSCE
      run: npm install -g @vscode/vsce
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx tsc

    - name: Package
      run: vsce package -o banjo-language.vsix

    - name: Release
      run: |
        gh release create \
          -t "banjo-vscode $(date -Idate)" \
          -n "banjo-vscode $(date -Idate)" \
          "$(date -Idate)" \
          banjo-language.vsix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
